import type { Metadata } from "next";
import { Belleza, Geist, Geist_Mono, Roboto, Ruda } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-roboto",
});

const belleza = Belleza({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-belleza",
});

const ruda = Ruda({
  subsets: ["latin"],
  weight: ["400", "700"], // Choisissez les poids désirés
  variable: "--font-ruda",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${ruda.variable} ${belleza.variable} ${roboto.variable}  antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
